# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# codeway.yaml
# Pipeline summary
# This is triggered both by pull requests and by merges to master branch.
# Some of the stages/jobs/scripts below are conditionally ran depending on how the pipeline was triggered.
resources:
    repositories:
      - repository: codeway
        type: githubenterprise
        name: codeway/templates
        endpoint: 
   
 # name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: # Trigger on branches
    batch: true
    branches:
      include:
        - master
pr: # Trigger on pull requests towards branches
    autoCancel: false
    branches:
      include:
        - master
  # Variable groups including configurations and secrets you want to use in this pipeline (Pipeline -> Library in ADO UI)
variables:
      - group: Defaults  
stages:
    - template: templates/mssi-win-dotnet-library-v0-alpha.yaml@codeway
      parameters:   
        isDotnetCore: true
        artifactName: 'buildArtifacts'
        restoreTargetDir: ''       
        restoreProjects: 'QuickStartCore.sln'
        buildArguments: '--configuration Release -o ./publish'
        artifactStagingDirectory: 'buildArtifacts'
        buildProjects: 'QuickStartCore.sln'
        testProjects: 'lib/TestLibrary/TestLibrary.csproj'
        testArguments: ''
        testWorkingDirectory: 'lib/TestLibrary/'
        packagesToPack: 'lib/TestLibrary/TestLibrary.csproj'
        packnoBuild: 'false'
        includeSymbols: 'true'
        includeSource: 'true'
        verbosityPack: 'Normal'
        versioningScheme: ''
        versionMajorMinor: '0.0'