# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
    repositories:
      - repository: azure-pipelines
        type: githubenterprise
        name: codeway/templates
        
  
trigger:
   - "*"
pr:
  - master


pool: CodeWayAWSWindows

  # Variable groups including configurations and secrets you want to use in this pipeline (Pipeline -> Library in ADO UI)
variables:
      - group: Defaults  
stages:
    - template: templates/mssi-win-dotnet-library-v0-alpha.yaml@codeway
    
      parameters:   
        isDotnetCore: true
        artifactName: 'buildArtifacts'
        restoreTargetDir: ''       
        restoreProjects: 'QuickStartCore.sln'
        buildArguments: '--configuration Release -o ./publish'
        artifactStagingDirectory: 'buildArtifacts'
        buildProjects: 'QuickStartCore.sln'
        testProjects: 'lib/TestLibrary/TestLibrary.csproj'
        testArguments: ''
        testWorkingDirectory: 'lib/TestLibrary/'
        packagesToPack: 'lib/TestLibrary/TestLibrary.csproj'
        packnoBuild: 'false'
        includeSymbols: 'true'
        includeSource: 'true'
        verbosityPack: 'Normal'
        versioningScheme: ''
        versionMajorMinor: '0.0'